/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agung.regresi.ui;

import com.agung.regresi.Main;
import com.agung.regresi.entity.Nilai;
import com.agung.regresi.ui.tableModel.DataTableModel;
import com.agung.regresi.util.CSVReader;
import com.agung.regresi.util.LookUtil;
import com.agung.regresi.util.TableUtil;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author agung
 */
public class DataPanel extends javax.swing.JInternalFrame {

    private List<Nilai> listData;
    private Nilai nilai;

    private static final Logger LOGGER = LoggerFactory.getLogger(DataPanel.class);

    public DataPanel() {
        initComponents();
        //loadDataToTable();
        setTitle("Data Training");
        //btnErase.setEnabled(false);
        LookUtil.plasticLaf(jToolBar1);
        TableUtil.initColumn(tblData, jScrollPane2);
        showTableHeader(false);
        loadDataToTable();
        tblData.getSelectionModel().addListSelectionListener(new TableSelection());
        tblData.setHighlighters(HighlighterFactory.createAlternateStriping());
    }

    public void showTableHeader(boolean status) {
        tblData.getTableHeader().setVisible(status);
    }

    private void loadDataToTable() {
        listData = Main.getDataRepository().getAllData();
        if (listData != null && !listData.isEmpty()) {
            showTableHeader(true);
            tblData.setModel(new DataTableModel(listData));
            TableUtil.initColumn(tblData, jScrollPane2);
        } else {
            tblData.setModel(new DataTableModel(new ArrayList<>()));
            TableUtil.initColumn(tblData, jScrollPane2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnNew = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnEdit = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnDelete = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        importBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnErase = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/colors_cmyk.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btnNew.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/add.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);
        jToolBar1.add(jSeparator3);

        btnEdit.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/box_edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);
        jToolBar1.add(jSeparator4);

        btnDelete.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/box_delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);
        jToolBar1.add(jSeparator5);

        importBtn.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        importBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/import.png"))); // NOI18N
        importBtn.setText("Csv Import");
        importBtn.setFocusable(false);
        importBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        importBtn.setVerifyInputWhenFocusTarget(false);
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(importBtn);
        jToolBar1.add(jSeparator2);

        btnErase.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnErase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/eraser_1.png"))); // NOI18N
        btnErase.setText("Clear Data");
        btnErase.setFocusable(false);
        btnErase.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnErase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnErase);

        jPanel2.setBackground(new java.awt.Color(207, 179, 179));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Siswa", "Nilai UAS", "Nilai UN"
            }
        ));
        tblData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Data Training");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(446, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        listData = new ArrayList<>();
        Main.getDataRepository().setData(listData);
        Main.getMainFrame().dataPanel = null;
        //Main.getMainFrame().getBtnData().doClick();
    }//GEN-LAST:event_formInternalFrameClosed

    private void changeTitle() {
        String titleBar = Main.getMainFrame().dataPanel.getTitle();
        Main.getMainFrame().dataPanel.setTitle(mFile.getName() + " - " + titleBar);
    }

    private JFileChooser fileChooser;
    private File mFile;
    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        mFile = new File("");
        if (fileChooser == null) {
            fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setFileFilter(
                    new FileNameExtensionFilter("csv", "csv")
            );
        }
        int ret = fileChooser.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            mFile = fileChooser.getSelectedFile();
            try {
                CSVReader reader = new CSVReader(mFile);
                List<Nilai> listNilai = reader.readFile();
                for (Nilai n : listNilai) {
                    System.out.println("Save data");
                    Main.getDataRepository().saveOrUpdate(n);
                }
                Main.getDataRepository().setData(listNilai);
                loadDataToTable();
                 JOptionPane.showMessageDialog(Main.getMainFrame(), "Import, OK");
                changeTitle();
                importBtn.setEnabled(false);
                btnErase.setEnabled(true);
            } catch (FileNotFoundException e) {
                LOGGER.debug(e.getMessage());
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(DataPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_importBtnActionPerformed

    private void btnEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "Anda yakin akan menghapus semua data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                mFile = new File("");
                Main.getDataRepository().deleteAll();
                listData = new ArrayList<>();
                Main.getDataRepository().setData(listData);
                Main.getMainFrame().dataPanel.setTitle("List Data");
                loadDataToTable();
                showTableHeader(false);
                importBtn.setEnabled(true);
                 JOptionPane.showMessageDialog(Main.getMainFrame(), "Clear, OK");
                //btnErase.setEnabled(false);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(DataPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEraseActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        nilai = new DialogData().showDialog();
        if (nilai != null) {
            try {
                Main.getDataRepository().saveOrUpdate(nilai);
                loadDataToTable();
                JOptionPane.showMessageDialog(Main.getMainFrame(), "Data Berhasil disimpan");
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(DataPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void editData(){
        if (tblData.getSelectedRow() >= 0 && nilai != null) {
            nilai = new DialogData().editDialog(nilai);
            if (nilai != null) {
                try {
                    Main.getDataRepository().saveOrUpdate(nilai);
                    loadDataToTable();
                     JOptionPane.showMessageDialog(Main.getMainFrame(), "Data Berhasil diubah");
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(DataPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(Main.getMainFrame(),
                    "Tidak ada data yang ingin di edit !!",
                    "Terjadi Kesalahan !!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (tblData.getSelectedRow() >= 0 && nilai != null) {
                Main.getDataRepository().delete(nilai);
                loadDataToTable();
                
            } else {
                JOptionPane.showMessageDialog(Main.getMainFrame(),
                        "Tidak ada data yang ingin di hapus !!",
                        "Terjadi Kesalahan !!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private class TableSelection implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                return;
            }
            if (tblData.getSelectedRow() >= 0) {
                nilai = listData.get(tblData.getSelectedRow());
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnErase;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton importBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTable tblData;
    // End of variables declaration//GEN-END:variables

}
