/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agung.regresi.ui;

import com.agung.regresi.Main;
import com.agung.regresi.entity.Nilai;
import com.agung.regresi.ui.tableModel.DataTableModel;
import com.agung.regresi.util.TableUtil;
import java.awt.Color;
import java.util.List;
import org.jdesktop.swingx.decorator.HighlighterFactory;

/**
 *
 * @author agung
 */
public class JXTableDemo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JXTableDemo
     */
    public JXTableDemo() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        List<Nilai> listData = Main.getDataRepository().getAllData();
        tblData.setModel(new DataTableModel(listData));

//        Highlighter simpleStriping = HighlighterFactory.createSimpleStriping();
//        PatternPredicate patternPredicate = new PatternPredicate("ˆM", 1);
//        ColorHighlighter magenta = new ColorHighlighter(patternPredicate, null,
//                Color.MAGENTA, null, Color.MAGENTA);
//        Highlighter shading = new ShadingColorHighlighter(
//                new HighlightPredicate.ColumnHighlightPredicate(1));

//        tblData.setHighlighters(simpleStriping,magenta,shading);
        tblData.setHighlighters(HighlighterFactory.createSimpleStriping());
        tblData.setSelectionBackground(Color.BLUE);
//        tblData.addHighlighter(new ColorHighlighter(HighlightPredicate.ROLLOVER_ROW,null,Color.LIGHT_GRAY));
        tblData.setColumnControlVisible(true);
        TableUtil.initColumn(tblData, jScrollPane1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new org.jdesktop.swingx.JXTable();

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable tblData;
    // End of variables declaration//GEN-END:variables
}
