/*
 *  MainFrame.java
 *  Prediksi-Nilai 
 * 
 *  Created by Agung Pramono on 17/09/2017 
 *  Copyright (c) 2017 Java Development. All rights reserved.
 */

package com.agung.regresi.ui;

import com.agung.regresi.util.LookUtil;
import java.beans.PropertyVetoException;
import javax.swing.JToggleButton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author agung
 */
public class MainFrame extends javax.swing.JFrame {

    private static final Logger LOGGER = LoggerFactory.getLogger(MainFrame.class);
    
    public MainFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle(".: Prediksi Nilai V.0.1 :.");
        LookUtil.plasticLaf(jToolBar1);
        LookUtil.plasticLaf(jMenuBar1);
        btnDemo.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        toolbarData = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        toolbarDataTesting = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        toolbarTest = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        toolbarChart = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnDemo = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 50));

        buttonGroup1.add(toolbarData);
        toolbarData.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        toolbarData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/data_copy.png"))); // NOI18N
        toolbarData.setToolTipText("Dataset");
        toolbarData.setFocusable(false);
        toolbarData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarDataActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarData);
        jToolBar1.add(jSeparator1);

        buttonGroup1.add(toolbarDataTesting);
        toolbarDataTesting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/data_unknown.png"))); // NOI18N
        toolbarDataTesting.setFocusable(false);
        toolbarDataTesting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarDataTesting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarDataTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarDataTestingActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarDataTesting);
        jToolBar1.add(jSeparator4);

        buttonGroup1.add(toolbarTest);
        toolbarTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/colors_cmyk.png"))); // NOI18N
        toolbarTest.setToolTipText("Testing");
        toolbarTest.setFocusable(false);
        toolbarTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarTestActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarTest);
        jToolBar1.add(jSeparator3);

        buttonGroup1.add(toolbarChart);
        toolbarChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/presentation_chart.png"))); // NOI18N
        toolbarChart.setToolTipText("Show Line Chart");
        toolbarChart.setFocusable(false);
        toolbarChart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarChart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarChartActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarChart);
        jToolBar1.add(jSeparator2);

        buttonGroup1.add(btnExit);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/delete.png"))); // NOI18N
        btnExit.setToolTipText("Exit Window");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);
        jToolBar1.add(jSeparator5);

        btnDemo.setText("Table");
        btnDemo.setFocusable(false);
        btnDemo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDemo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDemo);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel1.add(desktopPane, java.awt.BorderLayout.CENTER);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DataPanel dataPanel;     
    private void toolbarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarDataActionPerformed
        try {
            if (dataPanel ==  null) {
                dataPanel = new DataPanel();
                desktopPane.add(dataPanel);
            }else{
                dataPanel.toFront();
            }
            dataPanel.setVisible(true);
            dataPanel.setSelected(true);
//            dataPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            LOGGER.debug("[{}]", ex);
        }
    }//GEN-LAST:event_toolbarDataActionPerformed

    public ProcessPanel testingPanel;
    private void toolbarTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarTestActionPerformed
        try {
            if (testingPanel ==  null) {
                testingPanel = new ProcessPanel();
                desktopPane.add(testingPanel);
            }else{
                testingPanel.toFront();
            }
            testingPanel.setVisible(true);
            testingPanel.setSelected(true);
//            testingPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            LOGGER.debug("[{}]", ex);
        }
    }//GEN-LAST:event_toolbarTestActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    public ChartPanel chartPanel;
    private void toolbarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarChartActionPerformed
        try {
            if (chartPanel ==  null) {
                chartPanel = new ChartPanel();
                desktopPane.add(chartPanel);
            }else{
                chartPanel.toFront();
            }
            chartPanel.setVisible(true);
            chartPanel.setSelected(true);
            //testingPanel.setSize(800,800);
        } catch (PropertyVetoException ex) {
            LOGGER.debug("[{}]", ex);
        }
    }//GEN-LAST:event_toolbarChartActionPerformed

    public DataTestingPanel dataTestingPanel;
    private void toolbarDataTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarDataTestingActionPerformed
        try {
            if (dataTestingPanel ==  null) {
                dataTestingPanel = new DataTestingPanel();
                desktopPane.add(dataTestingPanel);
            }else{
                dataTestingPanel.toFront();
            }
            dataTestingPanel.setVisible(true);
            dataTestingPanel.setSelected(true);
            //testingPanel.setSize(800,800);
        } catch (PropertyVetoException ex) {
            LOGGER.debug("[{}]", ex);
        }
    }//GEN-LAST:event_toolbarDataTestingActionPerformed

    public JXTableDemo jXTableDemo;
    private void btnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoActionPerformed
        try {
            if (jXTableDemo ==  null) {
                jXTableDemo = new JXTableDemo();
                desktopPane.add(jXTableDemo);
            }else{
                jXTableDemo.toFront();
            }
            jXTableDemo.setVisible(true);
            jXTableDemo.setSelected(true);
            //testingPanel.setSize(800,800);
        } catch (PropertyVetoException ex) {
            LOGGER.debug("[{}]", ex);
        }
    }//GEN-LAST:event_btnDemoActionPerformed

    public JToggleButton getBtnData(){
        return toolbarData;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemo;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton toolbarChart;
    private javax.swing.JToggleButton toolbarData;
    private javax.swing.JToggleButton toolbarDataTesting;
    private javax.swing.JToggleButton toolbarTest;
    // End of variables declaration//GEN-END:variables

}
